version: "3.9"

services:
  iam-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iam-service
    restart: no
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
